global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: comments
    metrics_path: /prometheus
    static_configs:
      - targets:
          - 'comments:8081'
  - job_name: posts
    metrics_path: /prometheus
    static_configs:
      - targets:
          - 'ports:8080'

