datasources:
  - name: Prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Postgres Comments
    access: proxy
    type: postgres
    host: comments:4444
    database: comments
    user: postgres
    password: ''
    sslMode: disabled
  - name: Postgres Posts
    access: proxy
    type: postgres
    host: posts:5555
    database: posts
    user: postgres
    password: ''
    sslMode: disabled
  - name: Loki
    access: proxy
    type: loki
    url: loki:3100