micronaut:
  application:
    name: posts
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
datasources:
  default:
    url: jdbc:postgresql://posts-db:5432/posts
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
kafka.bootstrap.servers: kafka:9092
tracing:
  zipkin:
    enabled: true
    http:
      url: http://zipkin:9411
    sampler:
      probability: 1
