micronaut:
  application:
    name: posts
  server:
    port: 8080
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
endpoints:
  prometheus:
    sensitive: false
datasources:
  default:
    url: jdbc:postgresql://localhost:5555/posts
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 1
kafka.bootstrap.servers: localhost:9092