micronaut:
  application:
    name: comments
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
datasources:
  default:
    url: jdbc:postgresql://comments-db:5432/comments
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
tracing:
  zipkin:
    enabled: true
    http:
      url: http://zipkin:9411
    sampler:
      probability: 1
kafka.bootstrap.servers: kafka:9092
